package dev.minegame.mines;

import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import net.kyori.adventure.text.Component;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.block.*;
import org.bukkit.event.entity.CreatureSpawnEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.player.PlayerBucketEmptyEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.scheduler.BukkitTask;

/**
 * Shared cash-out game. The outcome path is generated server-side before the
 * chicken moves, then animated tile by tile so vanilla mob AI cannot affect it.
 */
public final class ChickenManager implements Listener {
    private static final List<String> COLORS=List.of("red","blue","gold","green");
    private final MinegamePlugin plugin; private final Economy economy; private final ChickenStationStorage storage; private final BlockSnapshotStorage restore; private final Map<String, Runtime> stations=new LinkedHashMap<>(); private final NamespacedKey chickenKey,holoKey; private BukkitTask task; private int animationTick; private boolean nativeChickenSpawn;
    public ChickenManager(MinegamePlugin plugin, Economy economy, ChickenStationStorage storage, BlockSnapshotStorage restore){this.plugin=plugin;this.economy=economy;this.storage=storage;this.restore=restore;chickenKey=new NamespacedKey(plugin,"chicken_runner");holoKey=new NamespacedKey(plugin,"chicken_hologram");for(ChickenStationData s:storage.all())stations.put(s.key(),new Runtime(s));}
    public void start(){for(Runtime r:stations.values()){purgeHolograms(r);build(r);render(r);}refreshHologramVisibility();task=PlatformScheduler.runTaskTimer(plugin,this::tick,2,2);}
    public void shutdown(){if(task!=null)task.cancel();for(Runtime r:stations.values())clearEntities(r);}
    public Collection<ChickenStationData> stations(){return storage.all();}
    public String color(String text){return ChatColor.translateAlternateColorCodes('&',text);}
    public void create(Player p,int size){if(size<5||size>15||size%2==0){p.sendMessage(color("&cSize must be odd, from 5 to 15."));return;}Location l=p.getLocation().getBlock().getLocation();ChickenStationData s=new ChickenStationData(l.getWorld().getName(),l.getBlockX(),l.getBlockY(),l.getBlockZ(),size);if(stations.containsKey(s.key())){p.sendMessage(color("&cA Chicken board already exists here."));return;}Runtime r=new Runtime(s);r.size=size;stations.put(s.key(),r);storage.upsert(s);storage.save();build(r);render(r);p.sendMessage(color("&aChicken board created. Bet with &f/chicken <red|blue|gold|green> <amount>&a."));}
    public void remove(Player p,int index){Runtime r=byIndex(index);if(r==null){p.sendMessage(color("&cUnknown Chicken board number."));return;}clearEntities(r);restore.restoreAndForget(r.station.key());stations.remove(r.station.key());storage.remove(r.station.key());storage.save();p.sendMessage(color("&eChicken board removed and original blocks restored."));}
    public void regen(Player p,String raw){Runtime r=raw==null?nearest(p):parseIndex(raw);if(r==null){p.sendMessage(color("&cStand near a Chicken board or give its number."));return;}clearEntities(r);build(r);render(r);p.sendMessage(color("&aChicken board regenerated."));}
    public void list(Player p){p.sendMessage(color("&6[Chicken] &fBoards: &e"+stations.size()));int i=1;for(Runtime r:stations.values())p.sendMessage(color("&e"+i+++". &f"+r.station.worldName()+" &7("+r.station.x()+", "+r.station.y()+", "+r.station.z()+") &b["+r.size+"x"+r.size+"]"));}
    public void reload(CommandSender sender){plugin.reloadConfig();for(Runtime r:stations.values()){r.lastLines=List.of();render(r);}refreshHologramVisibility();sender.sendMessage(color("&aChicken configuration reloaded."));}
    public Object current(String path){String full=path.startsWith("chicken.")?path:"chicken."+path;return plugin.getConfig().get(full);} public void set(Player p,String path,String raw){String full=path.startsWith("chicken.")?path:"chicken."+path;Object old=plugin.getConfig().get(full);if(old==null){p.sendMessage(color("&cInvalid Chicken setting: &f"+path));return;}try{Object value=old instanceof Boolean?Boolean.parseBoolean(raw):old instanceof Integer?Integer.parseInt(raw):old instanceof Double?Double.parseDouble(raw):raw;plugin.getConfig().set(full,value);plugin.saveConfig();for(Runtime r:stations.values()){if(full.startsWith("chicken.blocks.")||full.equals("chicken.dead-tile-count"))build(r);r.lastLines=List.of();render(r);}p.sendMessage(color("&aUpdated &f"+full+"&a to &f"+value));}catch(NumberFormatException ex){p.sendMessage(color("&cInvalid value."));}}
    public void placeBet(Player p,String selection,double amount){Runtime r=nearest(p);if(r==null){p.sendMessage(color("&cStand near a Chicken board."));return;}selection=selection.toLowerCase(Locale.ROOT);if(!COLORS.contains(selection)){p.sendMessage(color("&cChoose red, blue, gold, or green."));return;}if(r.phase==Phase.IDLE){r.phase=Phase.BETTING;r.left=cfgI("betting-seconds",10);}else if(r.phase!=Phase.BETTING){p.sendMessage(color("&cBetting is closed; wait for the next Chicken round."));return;}if(amount<cfgD("min-bet",1)||cfgD("max-bet",-1)>=0&&amount>cfgD("max-bet",-1)){p.sendMessage(color("&cThat wager is outside the allowed range."));return;}if(r.bets.containsKey(p.getUniqueId())){p.sendMessage(color("&cYou already have a Chicken wager this round."));return;}if(!economy.withdrawPlayer(p,amount).transactionSuccess()){p.sendMessage(color("&cYou do not have enough money."));return;}r.bets.put(p.getUniqueId(),new Bet(p.getName(),selection,amount));p.sendMessage(color("&aChicken wager: &f"+selection+" &7| &6$"+money(amount)+" &7| cash out before lightning."));render(r);}
    public void cashout(Player p){Runtime r=stations.values().stream().filter(x->x.bets.containsKey(p.getUniqueId())).findFirst().orElse(null);if(r==null||r.phase!=Phase.RUNNING){p.sendMessage(color("&cYou have no Chicken bet that can be cashed out."));return;}Bet bet=r.bets.get(p.getUniqueId());if(bet.cashed){p.sendMessage(color("&cYou already cashed out."));return;}double payout=Math.min(bet.amount*r.multiplier,cfgD("max-payout",-1)<0?Double.MAX_VALUE:cfgD("max-payout",-1));economy.depositPlayer(p,payout);bet.cashed=true;bet.payout=payout;r.paid+=payout;p.sendMessage(color("&aCashed out &6$"+money(payout)+" &7("+String.format(Locale.ROOT,"%.2f",r.multiplier)+"x)"));render(r);}
    private void tick(){animationTick++;for(Runtime r:stations.values()){if(r.phase==Phase.BETTING&&animationTick%10==0&&--r.left<=0)begin(r);else if(r.phase==Phase.RUNNING)advance(r);else if(r.phase==Phase.RESULT&&animationTick%10==0&&--r.left<=0)reset(r);animateFrame(r);render(r);}refreshHologramVisibility();}
    private void begin(Runtime r){randomizeTiles(r);r.phase=Phase.RUNNING;r.multiplier=1.0;r.step=0;int minTicks=Math.max(1,cfgI("min-lightning-seconds",5))*10;int maxTicks=Math.max(minTicks,Math.max(1,cfgI("max-lightning-seconds",45))*10);double lightningRoll=Math.pow(ThreadLocalRandom.current().nextDouble(),cfgD("lightning-randomness-curve",1.8));r.lightningTicksRemaining=minTicks+(int)Math.round((maxTicks-minTicks)*lightningRoll);r.route=route(r);spawnPickups(r);nativeChickenSpawn=true;try{r.chicken=r.station.centerLocation().getWorld().spawn(r.tile(r.route.getFirst()),Chicken.class);}finally{nativeChickenSpawn=false;}r.chicken.setAI(false);r.chicken.setInvulnerable(true);r.chicken.setPersistent(false);r.chicken.getPersistentDataContainer().set(chickenKey,PersistentDataType.STRING,r.station.key());}
    private void advance(Runtime r){r.multiplier+=cfgD("multiplier-increase-per-second",.03)/10.0;if(--r.lightningTicksRemaining<=0){strike(r);return;}if(r.chicken!=null&&r.chicken.isValid()){r.chicken.customName(Component.text(color("&e"+String.format(Locale.ROOT,"%.2fx",r.multiplier))));r.chicken.setCustomNameVisible(true);}if(r.chicken==null||!r.chicken.isValid()){strike(r);return;}if(r.step>=r.route.size()-1){r.route=route(r);r.step=0;spawnPickups(r);}Location current=r.chicken.getLocation();Location next=r.tile(r.route.get(r.step+1));org.bukkit.util.Vector direction=next.toVector().subtract(current.toVector());direction.setY(0);double distance=direction.length();if(distance>.36){direction.normalize();Location moved=current.add(direction.multiply(.36));moved.setDirection(direction);r.chicken.teleport(moved);return;}r.chicken.teleport(next);if(++r.step>=r.route.size()-1){return;}if(r.pickups.contains(r.step)){r.multiplier+=cfgD("pickup-multiplier",.25);UUID id=r.items.remove(r.step);Entity item=id==null?null:Bukkit.getEntity(id);if(item!=null)item.remove();Location sparkle=next.clone().add(0,.45,0);r.chicken.getWorld().spawnParticle(Particle.END_ROD,sparkle,22,.3,.35,.3,.04);r.chicken.getWorld().spawnParticle(Particle.FIREWORK,sparkle,16,.25,.3,.25,.03);r.chicken.getWorld().playSound(sparkle,Sound.ENTITY_EXPERIENCE_ORB_PICKUP,.9f,1.35f);}}
    private void strike(Runtime r){Location at=r.chicken!=null&&r.chicken.isValid()?r.chicken.getLocation():r.tile(r.route.getLast());World w=at.getWorld();w.strikeLightningEffect(at);w.spawnParticle(Particle.ELECTRIC_SPARK,at.clone().add(0,.5,0),35,.5,.6,.5,.1);if(r.chicken!=null)r.chicken.remove();r.chicken=null;for(UUID id:r.items.values()){Entity e=Bukkit.getEntity(id);if(e!=null)e.remove();}r.items.clear();String landed=tileColor(r,at);boolean dead=landed.equals("dead");for(Bet bet:r.bets.values())if(!bet.cashed&&landed.equals(bet.selection)&&!dead){double payout=Math.min(bet.amount*r.multiplier*bonus(landed),cfgD("max-payout",-1)<0?Double.MAX_VALUE:cfgD("max-payout",-1));Player p=Bukkit.getPlayerExact(bet.player);if(p!=null)economy.depositPlayer(p,payout);bet.payout=payout;r.paid+=payout;}r.result=dead?"DEAD TILE — NO BONUS":landed.toUpperCase(Locale.ROOT)+" "+String.format(Locale.ROOT,"%.2fx",bonus(landed));r.phase=Phase.RESULT;r.left=cfgI("result-seconds",6);}
    private void spawnPickups(Runtime r){for(UUID id:r.items.values()){Entity entity=Bukkit.getEntity(id);if(entity!=null)entity.remove();}r.items.clear();r.pickups=new HashSet<>();for(int i=3;i<r.route.size();i+=4)r.pickups.add(i);World world=Bukkit.getWorld(r.station.worldName());if(world==null)return;for(int i:r.pickups){ItemDisplay display=world.spawn(r.tile(r.route.get(i)).add(0,.25,0),ItemDisplay.class);display.setItemStack(new ItemStack(Material.NETHER_STAR));display.setPersistent(false);r.items.put(i,display.getUniqueId());}}private void reset(Runtime r){r.bets.clear();r.paid=0;r.phase=Phase.IDLE;r.left=0;r.result="";r.multiplier=1;}
    private List<Cell> route(Runtime r){List<Cell> all=new ArrayList<>();for(int z=0;z<r.size;z++)for(int x=0;x<r.size;x++)all.add(new Cell(x,z));Collections.shuffle(all);int maximum=Math.min(all.size(),cfgI("max-steps",40));int minimum=Math.min(maximum,Math.max(2,cfgI("min-steps",8)));int length=ThreadLocalRandom.current().nextInt(minimum,maximum+1);return new ArrayList<>(all.subList(0,length));}
    private String tileText(String color){return switch(color){case "red"->"&cRED";case "blue"->"&9BLUE";case "gold"->"&eGOLD";case "green"->"&aGREEN";default->"&8DEAD";};}private double bonus(String color){return cfgD(color+"-bonus",color.equals("green")?8:2);}
    private void build(Runtime r){World w=Bukkit.getWorld(r.station.worldName());if(w==null)return;List<Block> blocks=new ArrayList<>();int h=r.size/2;for(int dz=-h-1;dz<=h+1;dz++)for(int dx=-h-1;dx<=h+1;dx++)blocks.add(w.getBlockAt(r.station.x()+dx,r.station.y(),r.station.z()+dz));restore.captureIfAbsent(r.station.key(),blocks);for(int dz=-h-1;dz<=h+1;dz++)for(int dx=-h-1;dx<=h+1;dx++)if(Math.abs(dx)==h+1||Math.abs(dz)==h+1)w.getBlockAt(r.station.x()+dx,r.station.y(),r.station.z()+dz).setType(material("frame",Material.REDSTONE_LAMP),false);randomizeTiles(r);}private void randomizeTiles(Runtime r){World w=Bukkit.getWorld(r.station.worldName());if(w==null)return;int h=r.size/2,total=r.size*r.size,seen=0,remainingDead=Math.min(cfgI("dead-tile-count",10),total-4);ThreadLocalRandom random=ThreadLocalRandom.current();for(int dz=-h;dz<=h;dz++)for(int dx=-h;dx<=h;dx++){Block b=w.getBlockAt(r.station.x()+dx,r.station.y(),r.station.z()+dz);int cellsLeft=total-seen++;boolean dead=remainingDead>0&&random.nextInt(Math.max(1,cellsLeft))<remainingDead;if(dead){b.setType(material("dead",Material.BLACK_CONCRETE),false);remainingDead--;}else b.setType(tileMaterial(COLORS.get(random.nextInt(COLORS.size()))),false);}}
     private void render(Runtime r){if(!plugin.getConfig().getBoolean("chicken.hologram.enabled",true)){clearHolograms(r);return;}Location a=r.station.centerLocation().add(0,cfgD("hologram-height",4.5),0);List<String> lines=new ArrayList<>();lines.add("&6&lCHICKEN");if(r.phase==Phase.IDLE){lines.add("&f/chicken <colour> <amount>");lines.add("&fPick a tile; black tiles pay nothing.");}else if(r.phase==Phase.BETTING){lines.add("&e"+r.left+"s &7— &f/chicken <colour> <amount>");lines.add("&fPick a tile; black tiles pay nothing.");for(Bet bet:r.bets.values())lines.add("&f"+bet.player+" &7| "+tileText(bet.selection)+" &6$"+money(bet.amount));}else if(r.phase==Phase.RUNNING){lines.add("&eChicken is running — hit the frame or use &f/chicken cashout");for(Bet bet:r.bets.values())lines.add((bet.cashed?"&a✓ ":"&f")+bet.player+" &7| "+tileText(bet.selection)+" &6$"+money(bet.amount));}else{lines.add("&eLIGHTNING! &f"+r.result);lines.add("&7Next round in "+r.left+"s");}if(lines.equals(r.lastLines))return;clearHolograms(r);purgeHolograms(r);r.lastLines=List.copyOf(lines);for(int i=0;i<lines.size();i++){TextDisplay d=a.getWorld().spawn(a.clone().subtract(0,i*cfgD("hologram-line-spacing",.4),0),TextDisplay.class);d.text(Component.text(color(lines.get(i))));d.setBillboard(Display.Billboard.CENTER);d.setSeeThrough(plugin.getConfig().getBoolean("hologram.see-through-walls",true));HologramStyle.apply(plugin,d);d.setPersistent(false);d.setViewRange((float)Math.max(.01,cfgD("hologram-view-range",32)/64.0));d.getPersistentDataContainer().set(holoKey,PersistentDataType.STRING,r.station.key());r.holograms.add(d.getUniqueId());}}
    private void refreshHologramVisibility(){double range=Math.max(0.0,cfgD("hologram-view-range",32.0));double rangeSquared=range*range;for(Runtime r:stations.values())for(UUID id:r.holograms){Entity entity=Bukkit.getEntity(id);if(!(entity instanceof TextDisplay display))continue;for(Player player:Bukkit.getOnlinePlayers()){boolean visible=player.getWorld().equals(display.getWorld())&&player.getLocation().distanceSquared(display.getLocation())<=rangeSquared;if(visible)player.showEntity(plugin,display);else player.hideEntity(plugin,display);}}}
    private void purgeHolograms(Runtime r){World world=Bukkit.getWorld(r.station.worldName());if(world==null)return;for(Entity entity:world.getEntities())if(entity instanceof TextDisplay&&r.station.key().equals(entity.getPersistentDataContainer().get(holoKey,PersistentDataType.STRING)))entity.remove();}private void clearHolograms(Runtime r){for(UUID id:r.holograms){Entity e=Bukkit.getEntity(id);if(e!=null)e.remove();}r.holograms.clear();}
    private void clearEntities(Runtime r){clearHolograms(r);if(r.chicken!=null)r.chicken.remove();for(UUID id:r.items.values()){Entity e=Bukkit.getEntity(id);if(e!=null)e.remove();}r.items.clear();}
    @EventHandler(priority=EventPriority.HIGHEST) public void chickenFrameHit(BlockDamageEvent event){Runtime r=frameRuntime(event.getBlock());if(r==null)return;event.setCancelled(true);if(r.phase==Phase.RUNNING&&r.bets.containsKey(event.getPlayer().getUniqueId()))cashout(event.getPlayer());}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenBreak(BlockBreakEvent event){if(protectedBlock(event.getBlock())&&!event.getPlayer().hasPermission("chicken.admin"))event.setCancelled(true);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenPlace(BlockPlaceEvent event){if(protectedBlock(event.getBlockPlaced())&&!event.getPlayer().hasPermission("chicken.admin"))event.setCancelled(true);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenBucket(PlayerBucketEmptyEvent event){if(protectedBlock(event.getBlockClicked().getRelative(event.getBlockFace()))&&!event.getPlayer().hasPermission("chicken.admin"))event.setCancelled(true);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenFlow(BlockFromToEvent event){if(protectedBlock(event.getToBlock()))event.setCancelled(true);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenSpawn(CreatureSpawnEvent event){if(!nativeChickenSpawn&&protectedBlock(event.getLocation().getBlock()))event.setCancelled(true);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenEntityExplode(EntityExplodeEvent event){event.blockList().removeIf(this::protectedBlock);}
@EventHandler(priority=EventPriority.HIGHEST) public void chickenBlockExplode(BlockExplodeEvent event){event.blockList().removeIf(this::protectedBlock);}
private Runtime frameRuntime(Block block){for(Runtime r:stations.values()){if(!r.station.worldName().equals(block.getWorld().getName())||block.getY()!=r.station.y())continue;int h=r.size/2+1;int dx=Math.abs(block.getX()-r.station.x()),dz=Math.abs(block.getZ()-r.station.z());if((dx==h&&dz<=h)||(dz==h&&dx<=h))return r;}return null;}
private boolean protectedBlock(Block block){for(Runtime r:stations.values()){if(!r.station.worldName().equals(block.getWorld().getName()))continue;int h=r.size/2+1;if(block.getY()>=r.station.y()&&block.getY()<=r.station.y()+6&&Math.abs(block.getX()-r.station.x())<=h&&Math.abs(block.getZ()-r.station.z())<=h)return true;}return false;}private Runtime nearest(Player p){double max=cfgD("activation-distance",24);return stations.values().stream().filter(r->r.station.worldName().equals(p.getWorld().getName())).filter(r->p.getLocation().distanceSquared(r.station.centerLocation())<=max*max).min(Comparator.comparingDouble(r->p.getLocation().distanceSquared(r.station.centerLocation()))).orElse(null);}
    private Runtime byIndex(int n){return n<1||n>stations.size()?null:new ArrayList<>(stations.values()).get(n-1);} private Runtime parseIndex(String raw){try{return byIndex(Integer.parseInt(raw));}catch(NumberFormatException e){return null;}}
    private Material tileMaterial(String color){return material(color,switch(color){case "red"->Material.RED_CONCRETE;case "blue"->Material.BLUE_CONCRETE;case "gold"->Material.GOLD_BLOCK;case "green"->Material.LIME_CONCRETE;default->Material.BLACK_CONCRETE;});}private void animateFrame(Runtime r){World w=Bukkit.getWorld(r.station.worldName());if(w==null)return;int h=r.size/2+1;int index=0;for(int z=-h;z<=h;z++)for(int x=-h;x<=h;x++){if(Math.abs(x)!=h&&Math.abs(z)!=h)continue;Block b=w.getBlockAt(r.station.x()+x,r.station.y(),r.station.z()+z);org.bukkit.block.data.BlockData data=b.getBlockData();if(data instanceof org.bukkit.block.data.Lightable light)light.setLit(r.phase==Phase.RUNNING&&index++%3==animationTick%3);b.setBlockData(data,false);}}private Material material(String key,Material fallback){Material m=Material.matchMaterial(plugin.getConfig().getString("chicken.blocks."+key,fallback.name()));return m!=null&&m.isBlock()?m:fallback;} private String tileColor(Runtime r,Location l){Material m=l.getBlock().getType();if(m==material("dead",Material.BLACK_CONCRETE))return "dead";for(String c:COLORS)if(m==tileMaterial(c))return c;return "dead";}private double cfgD(String key,double fallback){return plugin.getConfig().getDouble("chicken."+key,fallback);}private int cfgI(String key,int fallback){return plugin.getConfig().getInt("chicken."+key,fallback);}private String money(double d){return String.format(Locale.ROOT,"%.2f",d);}
    private enum Phase{IDLE,BETTING,RUNNING,RESULT} private record Cell(int x,int z){} private static final class Bet{final String player,selection;final double amount;boolean cashed;double payout;Bet(String player,String selection,double amount){this.player=player;this.selection=selection;this.amount=amount;}}private static final class Runtime{final ChickenStationData station;int size,left,step,lightningTicksRemaining;Phase phase=Phase.IDLE;double multiplier=1,paid;String result="";List<Cell>route=List.of();Set<Integer>pickups=Set.of();Chicken chicken;Map<UUID,Bet>bets=new LinkedHashMap<>();Map<Integer,UUID>items=new HashMap<>();List<UUID>holograms=new ArrayList<>();List<String>lastLines=List.of();Runtime(ChickenStationData station){this.station=station;this.size=station.size();}Location tile(Cell c){int h=size/2;return station.centerLocation().add(c.x-h,0,c.z-h);}}
}
